version: '3'
services:
  web:
    build: .
    command: python backend/main.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: cogniverse_db
      POSTGRES_USER: cogniverse_user
      POSTGRES_PASSWORD: cogniverse_password
    volumes:
      - ./data/db:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - web
  nginx:
    build: ./deployment
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend
  redis:
    image: redis:alpine
  worker:
    build: .
    command: rq worker cogniverse-tasks
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
  test:
    build: .
    command: pytest
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
      - worker
      - frontend
      - nginx
